publication/urls.py
#!/usr/bin/env python
# encoding: utf-8
"""
urls.py

Created by Valder Gallo on 2012-01-29.
Copyright (c) 2012 valdergallo. All rights reserved.
"""

from django.conf.urls.defaults import patterns, url

puuublic/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps import GenericSitemap

from filebrowser.sites import site
admin.autodiscover()

from website.views import EmailView
from website.sitemap import sitemaps
from website.feed import RssSiteNewsFeed, AtomSiteNewsFeed
from publication.models import Publication

news = {
    'googlenews': GenericSitemap({
        'queryset': Publication.objects.order_by('-created_at'),
        'limit': 0.5,
        'changefreq': 'daily',
        'date_field': 'created_at'
    }),
}

urlpatterns = patterns('',
    url(r'^public_admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^public_admin/varnish/', include('varnishapp.urls')),
    url(r'^public_admin/', include(admin.site.urls)),
    url(r'^public_admin/filebrowser/', include(site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^email-template/?$', EmailView.as_view()),
    url(r'^sitemap-googlenews\.xml$', 'django.contrib.sitemaps.views.sitemap',
        { 'sitemaps': news , 'template_name': 'sitemap_googlenews.xml' }),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.index', {
        'sitemaps': sitemaps,
    }),
    url(r'^sitemap-(?P<section>.+)\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    url(r'^rss/$', RssSiteNewsFeed()),
    url(r'^atom/$', AtomSiteNewsFeed()),
    url(r'^', include('website.urls', app_name='website', namespace='website')),
)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
#!/usr/bin/env python
# encoding: utf-8

from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('website.views',
    url(r'^$', 'home', name='home'),
    url(r'^recuperar/(?P<user_id>\d+)/(?P<token_dev>\w+)/$', 'recover', name='recover_pass'),
    url(r'^publicacoes/$', 'publications', name='publications'),
    url(r'^dashboard/$', 'dashboard', name='dashboard'),
    url(r'^ajax_login/$', 'ajax_login', name='ajax_login'),
    url(r'^ajax_signup/$', 'ajax_signup', name='ajax_signup'),
    url(r'^ajax_recover/$', 'ajax_recover', name='ajax_recover'),
    url(r'^logout/$', 'weblogout', name='weblogout'),
    url(r'^institucional/$', 'institucional', name='institucional'),
    url(r'^termos/$', 'termos', name='termos'),
    url(r'^contato/$', 'contato', name='contato'),
    url(r'^conta/$', 'acc_config', name='acc_config'),
    url(r'^bem-vindo/$', 'welcome', name='welcome'),
    url(r'^perfil/(?P<user_id>\w+)/$', 'publications_user', name='publications_user'),
)

urlpatterns += patterns('publication.views',
    url(r'^ajax_add_favorite/$', 'ajax_add_favorite', name='ajax_add_favorite'),
    url(r'^puuublic/adicionar/$', 'publication_add', name='publication_add'),
    url(r'^puuublic/tema/adicionar/$', 'theme_add', name='theme_add'),
    url(r'^publicacao/puuublic/buscar/json/$', 'ajax_theme_search', name='ajax_theme_search'),
    url(r'^(?P<theme_slug>[\w-]+)/(?P<publication_slug>[\w-]+)/editar/$', 'edit_publication', name='edit_publication'),
    url(r'^(?P<theme_slug>[\w-]+)/(?P<publication_slug>[\w-]+)/$', 'publication_detail', name='publication_detail'),
    url(r'^(?P<theme_slug>[\w-]+)/$', 'theme_page', name='theme_page'),
)

friendship/models.py
#!/usr/bin/env python
# encoding: utf-8
"""
models.py

Created by Valder Gallo on 2012-01-29.
Copyright (c) 2012 valdergallo. All rights reserved.
"""
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.db import models
from django.core.urlresolvers import reverse

from core.models import DefaultFields

class UserProfile(DefaultFields):
    "Extending User with DefaultFields"
    user = models.OneToOneField(User)
    image = models.ImageField(upload_to="profile/%Y/%m/%d",
                              blank=True, null=True)
    url = models.URLField(null=True, blank=True)
    about = models.TextField(null=True, blank=True)
    newsletter = models.BooleanField(
        verbose_name="Deseja receber newsletter com novidades?",
        blank=True,
        default=True
    )
    birthday = models.DateField(verbose_name=u"Aniversário",
                                null=True, blank=True)
    country = models.CharField(max_length=100, verbose_name=u"País",
                               blank=True, null=True)
    city = models.CharField(max_length=200, verbose_name=u"Cidade",
                            blank=True, null=True)

    nickname = models.CharField(max_length=100, verbose_name=u'Url de Perfil',
                                blank=True, null=True)

    objects = models.Manager()


    @property
    def get_url(self):
        if self.user.get_profile().url:
            return self.url
        return self.user.get_profile().get_absolute_url()


    def get_absolute_url(self):
        if self.nickname:
            ident = self.nickname
        else:
            ident = self.user.id
        return reverse('website:publications_user', kwargs={
            'user_id': ident }
        )

    def profile_url(self):
        if self.url:
            return self.url
        return self.get_absolute_url()

def create_user_profile(sender, instance, created, **kwargs):
    "Signal to auto create user"
    if created:
        #gerar token aqui?
        UserProfile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)

publication/models.py
#!/usr/bin/env python
# encoding: utf-8
"""
Copyright (c) 2012 valdergallo. All rights reserved.
"""

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver

from django.conf import settings
from django.template.defaultfilters import slugify
from core.models import DefaultFields, DefaultGeoFields
from publication.managers import PublicationManager, CommentManager
from website.templatetags.default_image import random_image
from taggit.managers import TaggableManager


class Favorites(DefaultGeoFields):
    user = models.ForeignKey(User)
    theme = models.ForeignKey('Theme')
    __unicode__ = lambda self: u'{} favoritou {}'.format(self.user, self.theme)

class Theme(DefaultGeoFields):
    user = models.ForeignKey(User)
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    #url = models.SlugField(max_length=30, null=True, blank=True, db_index=True)

    def __unicode__(self):
        return self.title.title()

    def url(self):
        return "{}{}".format(settings.SITE_URL,self.get_absolute_url())


    @models.permalink
    def get_absolute_url(self):
        return ('website:theme_page',(),{
            'theme_slug': self.slug
        })

class Publication(DefaultGeoFields):
    "This is messages from one Publication"
    theme = models.ForeignKey(Theme, related_name='publications', \
        verbose_name=u"Tema",help_text=u"(selecione o tema da sua publicação)")
    user = models.ForeignKey(User, related_name='publications_set')
    title = models.CharField(max_length=255,verbose_name=u"Título")
    message = models.TextField(verbose_name=u"Mensagem")
    slug = models.SlugField(max_length=200)
    image = models.ImageField(verbose_name=u"Imagem da Publicação",upload_to='publication/%Y/%m/%d', null=True, blank=True)
    tags = TaggableManager(verbose_name=u"Tags da Publicação",help_text=u"(separe por vírgulas)",blank=True)
    published = models.BooleanField(default=True)

    #replicate count
    rated_count = models.IntegerField(default=0)
    watched_count = models.IntegerField(default=0)
    liked_count = models.IntegerField(default=0)

    objects = PublicationManager()

    class Meta:
        get_latest_by = ('-created_at',)

    def __unicode__(self):
        return self.title

    def image_default(self):
        return random_image()


    def url(self):
        return "{}{}".format(settings.SITE_URL,self.get_absolute_url())

    @models.permalink
    def get_absolute_url(self):
        return ('website:publication_detail', (), {
                'theme_slug': self.theme.slug ,
                'publication_slug': self.slug or 'pub',
            })



#publication signal
@receiver(pre_save, sender=Publication)
def check_slug(sender, instance, **kwargs):
    try:
        obj = Publication.objects.get(pk=instance.pk)
    except Publication.DoesNotExist:
        pass
    else:
        if not obj.slug == slugify(instance.title):
            nslug = slugify(instance.title)
            c = 0
            while Publication.objects.filter(theme=obj.theme,slug=nslug).count() > 0:
                c += 1
                nslug = '%s-%d'%(nslug, c)
            instance.slug = nslug



class PublicationImage(DefaultFields):
    message = models.CharField(max_length=250)
    image = models.ImageField(upload_to='Publication/%Y/%m/%d')
    user = models.ForeignKey(User, related_name='images_set')
    publication = models.ForeignKey(Publication, related_name='publication_images_set')

    def __unicode__(self):
        return self.description


class Comment(DefaultGeoFields):
    message = models.CharField(max_length=200)
    user = models.ForeignKey(User)
    publication = models.ForeignKey(Publication, related_name='comments_set')

    objects = CommentManager()

    def __unicode__(self):
        return self.message

website/models.py
#!/usr/bin/env python
# encoding: utf-8
"""
models.py

Created by Valder Gallo on 2012-01-29.
Copyright (c) 2012 valdergallo. All rights reserved.
"""

from django.db import models
from core.models import DefaultGeoFields
from core.managers import ActiveManager


class Contact(models.Model):
    name = models.CharField(max_length=100, help_text=u"Qual o seu nome completo?")
    city = models.CharField(blank=True, max_length=100, help_text=u"Diga-nos de onde você é")
    email = models.EmailField(help_text=u"Qual é o seu e-mail?")
    fone = models.CharField(blank=True, max_length=100, help_text=u"Qual é o seu telefone com DDD?")
    message = models.TextField(blank=True, help_text=u"Digite a mensagem")
    date_send = models.DateField(auto_now_add=True)

    def __unicode__(self):
        return self.email

class Category(models.Model):
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name


class BlogManager(ActiveManager):

    def lastest_five(self):
        return self.all().order_by('-created_at')[0:5]


class Blog(DefaultGeoFields):
    title = models.CharField(max_length=255)
    tie = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, null=True, blank=True)
    message = models.TextField()
    image = models.ImageField(upload_to='publication/%Y/%m/%d')
    category = models.ManyToManyField(Category)

    objects = BlogManager()

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
            return ('blog', (), {
                'slug': self.slug,
            })

publication/forms.py
#!/usr/bin/env python
# encoding: utf-8
from django.conf import settings
from django import forms
from django.db.models import Q
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

from publication.models import Publication, Theme, Comment

from bs4 import BeautifulSoup
from ckeditor.widgets import CKEditorWidget

class SearchForm(forms.Form):
    "Search values on Publication content everywere"
    search = forms.CharField(max_length=100, required=False,\
        widget=forms.TextInput(attrs={'placeholder':'Busque aqui..',\
            'class':'search-large'} ))

    def get_result_queryset(self):
        query = Q()
        value = self.data.get('search', '')
        #_filter = self.data.get('filter', 'publication')

        #if _filter == 'publication':
        query |= Q(title__icontains=value)
        query |= Q(theme__title__icontains=value)
        query |= Q(message__icontains=value)
        query |= Q(tags__name__icontains=value)
        publications =  Publication.objects.select_related('themes').filter(query).order_by('-created_at')
        query = Q()

        #if _filter == 'puuublic':
        query |= Q(title__icontains=value)
        themes =  Theme.objects.filter(query)
        
        query = Q()
        #if _filter == 'people':
        query |= Q(first_name__icontains=value)
        query |= Q(last_name__icontains=value)
        query |= Q(username__icontains=value)

        people = User.objects.filter(query)

        count = publications.count() + themes.count() + people.count()
        return {
            'publications':publications,
            'people':people,
            'themes':themes,
            'count':count
        }


class PublicationForm(forms.ModelForm):
    "Add new Publication"
    theme_name = forms.CharField(label=u"Nome do Puuublic",max_length=50,\
        required=True,widget=forms.TextInput(attrs={'class':'theme-large'}),\
        error_messages={
            'required':u'Escolha um puuublic',
        })

    title = forms.CharField(widget=forms.TextInput(attrs={'class':'theme-large'}),\
        error_messages={
            'required':u'Escolha um Título'
        })

    message = forms.CharField(widget=CKEditorWidget(attrs={'cols': 80, 'rows': 30}),
            error_messages={'required':u'Digite uma mensagem'}
        )


    class Meta:
        model = Publication
        fields = ('theme_name','title', 'message', 'image')

    def clean_message(self):
        message = self.cleaned_data.get('message')
        #links externos adicionando _blank
        soup = BeautifulSoup(message)
        for link in soup.findAll('a'):
            link.attrs['target'] = '_blank'
        return unicode(soup)


    def clean_theme_name(self):
        title = self.cleaned_data['theme_name']
        try:
            Theme.objects.get(title=title)
        except Theme.DoesNotExist:
            raise forms.ValidationError(u'Tema Inválido')

        return title

    def clean_image(self):
        image = self.cleaned_data.get('image')
        if image:
            if image._size > settings.MAX_UPLOAD_SIZE:
                raise forms.ValidationError(u'Tamanho limite da imagem: 3MB')
        return image


    def save(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        theme = Theme.objects.get(title=self.cleaned_data['theme_name'])
        instance =  super(PublicationForm, self).save(commit=False)
        if not instance.slug:
            nslug = slugify(self.cleaned_data['title'])
            c = 0
            while Publication.objects.filter(theme=theme,slug=nslug).count() > 0:
                c += 1
                nslug = '%s-%d'%(nslug, c)
            instance.slug = nslug
        if user:
            instance.user = user
        if theme:
            instance.theme = theme
        instance.save()
        return instance



class ThemeForm(forms.ModelForm):
    "Create a new puublic"
    title = forms.CharField(max_length=50, required=True,\
        widget=forms.TextInput(attrs={\
            'class':'theme-large',
        }))

    def clean_title(self):
        title = self.cleaned_data['title']
        placeholder = u'Digite o nome do novo puuublic (Máximo 50 caracteres)'
        if title == '' or title == placeholder:
            raise forms.ValidationError(u'Digite um título')

        return title

    class Meta:
        model = Theme
        fields = ('title',)

class CommentForm(forms.ModelForm):
   
    message = forms.CharField(label=u"Mensagem",max_length=200,widget=forms.TextInput(attrs={
            'class':'theme-large',
        }))
 
    class Meta:
        model = Comment
        fields = ('message',)

website/forms.py
#!/usr/bin/env python
# encoding: utf-8
from django import forms
from website.models import Contact
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.localflavor.br.forms import BRPhoneNumberField


class ContactForm(forms.ModelForm):
    "Register contact form and send email"

    name = forms.CharField(error_messages={'required':u'Nome é campo obrigatório'})
    email = forms.EmailField(error_messages={'required':u'Email é campo obrigatório'})

    fone = BRPhoneNumberField(help_text=u"Ex: 99-9999-9999",required=False,\
        error_messages={'invalid':u'Informe um número no formato XX-XXXX-XXXX'})

    message = forms.CharField(widget=forms.Textarea,error_messages={
        'required':u"Digite uma mensagem"
    })

    class Meta:
        model = Contact


    def send_email(self):
        #TODO: send email default
        msg = u"""
        Date: %(date_send)s \n
        Nome: %(name)s \n
        Telefone: %(fone)s \n
        Cidade: %(city)s \n
        Mensagem: %(message)s
        """ % (self.instance.__dict__)

        sent = send_mail('[Puuublic] Contato ', msg,
        settings.NO_REPLY_EMAIL,[self.instance.email] )
        return True if sent == 1 else False

    def save(self, *args, **kwargs):
        self.send_email()
        super(ContactForm, self).save(*args, **kwargs)

website/templates/website/acc_config.html
{% extends 'base.html' %}
{% load i18n thumbnail default_image endless %}

{% block main %}
<div class="container config">
    {% if acc_config_form.errors or edit_user_form.errors %}
    <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <h4 class="alert-heading">Alguns erros foram encontrados</h4>
        <ul>
        {% for field in acc_config_form %}
        {% if field.errors %}
        <li>{{ field.errors|striptags }}</li>
        {% endif %}
        {% endfor %}
        {% for field in edit_user_form %}
        {% if field.errors %}
        <li>{{ field.errors|striptags }}</li>
        {% endif %}
        {% endfor %}
        </ul>
    </div>
    {% endif %}
    <h2>Configurações</h2>
    <hr/>
    <div class="row">
        <br/>
        <form enctype="multipart/form-data" method='POST' action='.'>
        <div class="span6">
            {% csrf_token %}
            <label for="id_first_name">Nome</label>
            {{ edit_user_form.first_name }}
            
            <label for="id_data_bourn">Data de Nascimento</label>
            {{ acc_config_form.birthday }}
            
            <label for="id_country">País</label>
            {{ acc_config_form.country }}

 
        </div>
        <div class="span6">
            <label for="id_last_name">Sobrenome</label>
            {{ edit_user_form.last_name }}

            <label for="id_gender">Gênero</label>
            {{ acc_config_form.gender }}
        
            <label for="id_city">Cidade</label>
            {{ acc_config_form.city }}
        
        </div>
    </div>
    <hr class="config-hr" />
    <div class="row">
        <div class="span6">
            <label for="id_image">Adicione uma foto no seu perfil</label>
            {{ acc_config_form.image }}
        </div>
        <div class="span6">
            <label for="id_url">Página Pessoal</label>
            {{ acc_config_form.url }}
        </div>
        <div class="span6">
            <label for="id_nickname">Apelido Puuublic</label>
            {{ acc_config_form.nickname }}
            <br/>
            <span>Seu endereço ficará: <span class="nickname-preview">http://</span>
        </div>

    </div>
    <div class="row">
        <div class="span12">
            <p>{{ acc_config_form.newsletter }} Deseja receber newsletter com novidades?</p>
        </div>
    </div>
    <div class="row">
        <div class="span12 config-right">
            <input type="submit" class="grey-button" value="Salvar" />
        </div>
    </div>
  <span>Para encerrar sua conta, envie um email para <a href="mailto:contact@puuublic.com?subject=Quero+encerrar+minha+conta">contact@puuublic.com</a>.
  <br/>
</form>
{% endblock  %}

website/templates/website/contact.html
{% extends 'base.html' %}

{% block main %}
<div class="container contato">
	<div class="row">
        <div class="span">
            <h2>Contato</h2>
            <hr/>
            <br/>
		    <p>Quer fazer reclamações, tem uma sugestão para melhorar o site ou quer nos enviar uma pergunta?<br>
		    Então mande-nos uma mensagem sobre esses e outros assuntos, estamos sempre ouvindo os usuários e fazendo o possível para responder rapidamente. Ou se preferir envie um e-mail para <a href="mailto:contact@puuublic.com">contact@puuublic.com</a></p>
	    </div>
    </div>
	<div class="row">
        <form action="{% url website:contato %}" id="formContact" method="POST" onsubmit="return false">
            <div class="span">
                {% csrf_token %}
                    <label for="id_name" title="{{ form.name.help_text }}">Nome*</label>
                    {{ form.name }}
                    <label for="id_city" title="{{ form.city.help_text }}">Cidade</label>
                    {{ form.city }}
                    <label for="id_email" title="{{ form.email.help_text }}">E-mail*</label>
                    {{ form.email }}
                    <label for="id_fone" title="{{ form.fone.help_text }}">Telefone</label>
                    {{ form.fone }}
                    <br/>
                    <span>{{ form.fone.help_text }}</span>
            </div>
            <div class="span">
                <label for="id_message" title="{{ form.message.help_text }}">Mensagem</label>
                {{ form.message }}
                <div class="row">
                    <div class="span">
                        <span>*Preenchimento obrigatório</span>
                    </div>
                    <div class="span right">
                        <input type="submit" class="green-button" value="Enviar" />
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<br/>
{% endblock  %}

website/templates/website/home.html
{% extends 'base.html' %}
{% load i18n thumbnail %}

{% block wrapper %}
{% if user.is_authenticated %}
Autenticado -.-
{% else %}
<section class='left_column'>
    <h3>O jeito mais legal de contar as novidades
    e ficar por dentro do que te interessa.</h3>
    <article>
        <figure>
            <img src="{{ STATIC_URL }}image/home-criar.png">
        </figure>
        <h4>Você pode criar um puuublic</h4>
        <div>
            Crie uma página pública para sua cidade, bairro, colégio,
            empresa, família, time, artista favorito ou qualquer assunto.
        </div>
    </article>
    <article>
        <figure>
            <img src="{{ STATIC_URL }}image/home-divulgar.png">
        </figure>
        <h4>Conte as novidade para todos</h4>
        <div>
            Publique textos, fotos e vídeos em qualquer puuublic.
            Conte para todo mundo o que é novidade para você.
        </div>
    </article>
    <article>
        <figure>
            <img src="{{ STATIC_URL }}image/home-favoritar.png">
        </figure>
        <h4>É mais fácil com os Favoritos</h4>
        <div>
            Favorite puuublics e pessoas e receba todas as Publicationações
            de seus favoritos e as mais populares em uma única página.
        </div>
    </article>
    <article>
        <figure>
            <img src="{{ STATIC_URL }}image/home-publicar.png">
        </figure>
        <h4>Divulgue com um clique</h4>
        <div>
            Gostou de alguma Publicationação? Envie para todos
            os seus leitores com apenas um clique.
        </div>
    </article>
    <article>
        <h4>Pesquise no Puuublic:</h4>
        <div>
            Encontre Publicationações, puuublics e pessoas.
        </div>
        <form action="{% url website:home %}" method="POST" name="search_Publication">
             {% include 'search_form.html' %}
        </form>
    </article>
</section>
<section class='right_column input_label'>
    <article>
        <h4>Já tem uma conta no Puuublic?</h4>
        <div>
            Digite usuário e senha. <a href='#'>Esqueceu?</a>
        </div>
        <form name='signin_form' id='id_signin_form' method='POST' action="{% url website:ajax_login %}" onsubmit='return false'>
            {% csrf_token %}
            <ul class='login_user'>
                {{ login_form.as_ul }}
                <li>
                    <input type='submit' value='Enviar' class='btn'>
                </li>
                <li class='error'></li>
            </ul>
        </form>
    </article>
    <article>
        <h4>Ainda não tem uma conta?</h4>
        <div>
            Crie uma conta agora mesmo. É rápido e de graça.
        </div>
        <form id="id_signup_form" name='signup_form' method='POST' action='{% url website:ajax_signup %}'
        onsubmit="return false">
            {% csrf_token %}
            <ul class="signupErrors">

            </ul>
            <ul class="register_form">
                {{ register_form.as_ul }}
                <li>
                    <input type='submit' class='send_large' value="Enviar" />
                </li>
            </ul>
        </form>
        <div id="modal">
            <h2 class="confirm">Puuublic</h2>
            <p></p>
        </div>
    </article>
</section>
<hr>
{% if must_popular_publication_list %}
<section class="must_popular">
    <h4>Publicationações mais populares</h4>
    {% for pub in must_popular_publication_list %}
    <article>
		{% thumbnail pub.image "67" as im %}
		<figure>
			<img src="{{ im.url }}" title="{{ pub.title }}" width="{{ im.width }}" height="{{ im.height }}">
		</figure>
		{% empty %}
		<figure>
			<img src="{{ default.image.url }}" title="{{ pub.title }}" width="{{ default.image.width }}" height="{{ default.image.height }}">
		</figure>
		{% endthumbnail %}
        {{ publication.title }}
        <div>
            no puuublic <a href="#">{{ publication.user.username }}</a>
        </div>
    </article>
    {% endfor %}
</section>
{% endif %}

{% if last_publication_list %}
<section class="last_publication_list">
    <h4>Publicationações mais recentes</h4>
    {% for pub in last_publication_list %}
    <article>
		{% thumbnail pub.image "67" as im %}
		<figure>
			<img src="{{ im.url }}" title="{{ pub.title }}" width="{{ im.width }}" height="{{ im.height }}">
		</figure>
		{% empty %}
		<figure>
			<img src="{{ default.image.url }}" title="{{ pub.title }}" width="{{ default.image.width }}" height="{{ default.image.height }}">
		</figure>
		{% endthumbnail %}
        {{ publication.title }}
        <div>
            no puuublic <a href="#">{{ publication.user.username }}</a>
        </div>
    </article>
    {% endfor %}
</section>
{% endif %}

{% endif %}
{% endblock wrapper %}

{% block js %}
{{ block.super }}
{% endblock js %}

website/templates/website/logged_out.html
{% if user.is_authenticated %}
<!-- Authenticate account menu -->
{% else %}
<h3>Login</h3>
<form action="/login/" method="post" accept-charset="utf-8">
<label for="username">Username</label><input type="text" name="username" value="" id="username" />
<label for="password">Password</label><input type="password" name="password" value="" id="password" />
<p><input type="submit" value="Login →"></p>
</form>
{% endif %}

website/templates/website/novidades.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block wrapper %}
<section>
	{% for blog in blog_list %}
		<article>
			{% thumbnail blog.image "100" as im %}
				<figure><img src="{{ im.url }}" title="{{ blog.title }}" width="{{ im.width }}" height="{{ im.height }}"></figure>
			{% endthumbnail %}
			<h4>{{ blog.title }}</h4> 
			<span>{{ blog.created_at|date:"d-m-Y"}}</span>
			<h5>{{ blog.tie }}</h5>
			<blockout>
				{{ blog.message }}
			</blockout>
		</article>
	{% empty %}
		<article>
			<h4> Nenhuma novidade cadastrada </h4>
		</article>
	{% endfor %}
</section>
{% endblock wrapper %}

website/templates/website/recover.html
{% extends 'base.html' %}
{% load i18n thumbnail %}

{% block main %}
<div class="container publication-add">
    <h2>Recuperação de Senha</h2>
    <br/>
    {% if form.errors %}
    {{form.non_field_errors}}
    {% endif %}
    <form method='POST' action="." >
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value='Enviar' class='green-button'>
        <div class='error'></li>
    </form>
</div>
<hr>
{% endblock  %}