puuublic/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps import GenericSitemap

from filebrowser.sites import site
admin.autodiscover()

from website.views import EmailView
from website.sitemap import sitemaps
from website.feed import RssSiteNewsFeed, AtomSiteNewsFeed
from publication.models import Publication

news = {
    'googlenews': GenericSitemap({
        'queryset': Publication.objects.order_by('-created_at'),
        'limit': 0.5,
        'changefreq': 'daily',
        'date_field': 'created_at'
    }),
}

urlpatterns = patterns('',
    url(r'^public_admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^public_admin/varnish/', include('varnishapp.urls')),
    url(r'^public_admin/', include(admin.site.urls)),
    url(r'^public_admin/filebrowser/', include(site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^email-template/?$', EmailView.as_view()),
    url(r'^sitemap-googlenews\.xml$', 'django.contrib.sitemaps.views.sitemap',
        { 'sitemaps': news , 'template_name': 'sitemap_googlenews.xml' }),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.index', {
        'sitemaps': sitemaps,
    }),
    url(r'^sitemap-(?P<section>.+)\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    url(r'^rss/$', RssSiteNewsFeed()),
    url(r'^atom/$', AtomSiteNewsFeed()),
    url(r'^', include('website.urls', app_name='website', namespace='website')),
)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
#!/usr/bin/env python
# encoding: utf-8

from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('website.views',
    url(r'^$', 'home', name='home'),
    url(r'^recuperar/(?P<user_id>\d+)/(?P<token_dev>\w+)/$', 'recover', name='recover_pass'),
    url(r'^publicacoes/$', 'publications', name='publications'),
    url(r'^dashboard/$', 'dashboard', name='dashboard'),
    url(r'^ajax_login/$', 'ajax_login', name='ajax_login'),
    url(r'^ajax_signup/$', 'ajax_signup', name='ajax_signup'),
    url(r'^ajax_recover/$', 'ajax_recover', name='ajax_recover'),
    url(r'^logout/$', 'weblogout', name='weblogout'),
    url(r'^institucional/$', 'institucional', name='institucional'),
    url(r'^termos/$', 'termos', name='termos'),
    url(r'^contato/$', 'contato', name='contato'),
    url(r'^conta/$', 'acc_config', name='acc_config'),
    url(r'^bem-vindo/$', 'welcome', name='welcome'),
    url(r'^perfil/(?P<user_id>\w+)/$', 'publications_user', name='publications_user'),
)

urlpatterns += patterns('publication.views',
    url(r'^ajax_add_favorite/$', 'ajax_add_favorite', name='ajax_add_favorite'),
    url(r'^puuublic/adicionar/$', 'publication_add', name='publication_add'),
    url(r'^puuublic/tema/adicionar/$', 'theme_add', name='theme_add'),
    url(r'^publicacao/puuublic/buscar/json/$', 'ajax_theme_search', name='ajax_theme_search'),
    url(r'^(?P<theme_slug>[\w-]+)/(?P<publication_slug>[\w-]+)/editar/$', 'edit_publication', name='edit_publication'),
    url(r'^(?P<theme_slug>[\w-]+)/(?P<publication_slug>[\w-]+)/$', 'publication_detail', name='publication_detail'),
    url(r'^(?P<theme_slug>[\w-]+)/$', 'theme_page', name='theme_page'),
)

publication/forms.py
#!/usr/bin/env python
# encoding: utf-8
from django.conf import settings
from django import forms
from django.db.models import Q
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

from publication.models import Publication, Theme, Comment

from bs4 import BeautifulSoup
from ckeditor.widgets import CKEditorWidget

class SearchForm(forms.Form):
    "Search values on Publication content everywere"
    search = forms.CharField(max_length=100, required=False,\
        widget=forms.TextInput(attrs={'placeholder':'Busque aqui..',\
            'class':'search-large'} ))

    def get_result_queryset(self):
        query = Q()
        value = self.data.get('search', '')
        #_filter = self.data.get('filter', 'publication')

        #if _filter == 'publication':
        query |= Q(title__icontains=value)
        query |= Q(theme__title__icontains=value)
        query |= Q(message__icontains=value)
        query |= Q(tags__name__icontains=value)
        publications =  Publication.objects.select_related('themes').filter(query).order_by('-created_at')
        query = Q()

        #if _filter == 'puuublic':
        query |= Q(title__icontains=value)
        themes =  Theme.objects.filter(query)
        
        query = Q()
        #if _filter == 'people':
        query |= Q(first_name__icontains=value)
        query |= Q(last_name__icontains=value)
        query |= Q(username__icontains=value)

        people = User.objects.filter(query)

        count = publications.count() + themes.count() + people.count()
        return {
            'publications':publications,
            'people':people,
            'themes':themes,
            'count':count
        }


class PublicationForm(forms.ModelForm):
    "Add new Publication"
    theme_name = forms.CharField(label=u"Nome do Puuublic",max_length=50,\
        required=True,widget=forms.TextInput(attrs={'class':'theme-large'}),\
        error_messages={
            'required':u'Escolha um puuublic',
        })

    title = forms.CharField(widget=forms.TextInput(attrs={'class':'theme-large'}),\
        error_messages={
            'required':u'Escolha um Título'
        })

    message = forms.CharField(widget=CKEditorWidget(attrs={'cols': 80, 'rows': 30}),
            error_messages={'required':u'Digite uma mensagem'}
        )


    class Meta:
        model = Publication
        fields = ('theme_name','title', 'message', 'image')

    def clean_message(self):
        message = self.cleaned_data.get('message')
        #links externos adicionando _blank
        soup = BeautifulSoup(message)
        for link in soup.findAll('a'):
            link.attrs['target'] = '_blank'
        return unicode(soup)


    def clean_theme_name(self):
        title = self.cleaned_data['theme_name']
        try:
            Theme.objects.get(title=title)
        except Theme.DoesNotExist:
            raise forms.ValidationError(u'Tema Inválido')

        return title

    def clean_image(self):
        image = self.cleaned_data.get('image')
        if image:
            if image._size > settings.MAX_UPLOAD_SIZE:
                raise forms.ValidationError(u'Tamanho limite da imagem: 3MB')
        return image


    def save(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        theme = Theme.objects.get(title=self.cleaned_data['theme_name'])
        instance =  super(PublicationForm, self).save(commit=False)
        if not instance.slug:
            nslug = slugify(self.cleaned_data['title'])
            c = 0
            while Publication.objects.filter(theme=theme,slug=nslug).count() > 0:
                c += 1
                nslug = '%s-%d'%(nslug, c)
            instance.slug = nslug
        if user:
            instance.user = user
        if theme:
            instance.theme = theme
        instance.save()
        return instance



class ThemeForm(forms.ModelForm):
    "Create a new puublic"
    title = forms.CharField(max_length=50, required=True,\
        widget=forms.TextInput(attrs={\
            'class':'theme-large',
        }))

    def clean_title(self):
        title = self.cleaned_data['title']
        placeholder = u'Digite o nome do novo puuublic (Máximo 50 caracteres)'
        if title == '' or title == placeholder:
            raise forms.ValidationError(u'Digite um título')

        return title

    class Meta:
        model = Theme
        fields = ('title',)

class CommentForm(forms.ModelForm):
   
    message = forms.CharField(label=u"Mensagem",max_length=200,widget=forms.TextInput(attrs={
            'class':'theme-large',
        }))
 
    class Meta:
        model = Comment
        fields = ('message',)

templates/base.html
{% load i18n thumbnail default_image endless %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<html lang="pt-BR">
<head>
    <meta charset='UTF-8'/>
    <meta name="google-site-verification" content="6qB7DMaU71CEg6gSjNxo-ACXMKyPYxRQuT3-qjK11L4" />
    {% block meta %}
    <meta name="viewport" content="width=device-width">
    <meta name=”robots” content="all">
    <meta name="distribution" content="global">
    <meta name="document" content="resource-type">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta content="pt" name="language">
    <meta content="pt-BR" name="content-language">
    {% endblock meta %}
    {% block extra_meta %}
    <meta name="description" content="Puuublic - Quais as novidades?">
    <meta name="keywords" content="HTML, tags, commands">
    {% endblock %}
    <meta property="fb:admins" content="847295023">
    {% block ogtags %}
    <!-- OG -->
    <meta property="og:image" content="http://puuublic.com/static/img/oglogo.png"/>
    <meta property="og:title" content="Puuublic - Quais as novidades?"/>
    <meta property="og:description" content="Conte as novidades e fique por dentro do que te interessa. Crie páginas públicas e compartilhe textos, fotos e vídeos." />
    <meta property="og:type" content="website"/>
    <meta property="og:site_name" content="Puuublic"/>
    <meta property="og:url" content="http://puuublic.com"/>
    {% endblock %}
    {% block seo %}

    {% endblock %}
    <title>{% block title %}Puuublic {% endblock title %}</title>
    <link title="Puuublic - Feed" href="htttp://puuublic.com/atom/" type="application/atom+xml" rel="alternate">
    <link rel="shortcut icon" href="/favicon.ico" />
    <link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.css" type="text/css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}css/mvp.css" type="text/css"/>
    {% block js %}
    <script>
      var analytics=analytics||[];analytics.load=function(e){var t=document.createElement("script");t.type="text/javascript",t.async=!0,t.src=("https:"===document.location.protocol?"https://":"http://")+"d2dq2ahtl5zl1z.cloudfront.net/analytics.js/v1/"+e+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(t,n);var r=function(e){return function(){analytics.push([e].concat(Array.prototype.slice.call(arguments,0)))}},i=["identify","track","pageview","ab"];for(var s=0;s<i.length;s++)analytics[i[s]]=r(i[s])},
      analytics.load("tsb35odt0o");
    </script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{{ STATIC_URL }}js/vendor/jquery-1.8.0.min.js"><\/script>')</script>
    <script src="{{ STATIC_URL }}js/vendor/bootstrap.min.js"></script>
    <script src="{{ STATIC_URL }}js/plugins.js"></script>
    <script src="{{ STATIC_URL }}js/jquery-ui.min.js"></script>
    <script src="{{ STATIC_URL }}js/jquery.tools.min.js"></script>
    <script src="{{ STATIC_URL }}js/vendor/modernizr-2.6.1-respond-1.1.0.min.js"></script>
    <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    {% endblock js %}
    {% block extrajs %}
    {% endblock %}
    {% block extra_header %}
    {% endblock %}
</head>
<body>
    {% include 'includes/facebook.html' %}
    <!--[if lt IE 7]>
        <p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p>
    <![endif]-->
    {% if request.path == '/'  %}
    {% include 'includes/navindex.html'%}
    {% else %}
    {% include 'includes/nav.html'%}
    {% endif %}
    {% block main %}
    <div class="hero-unit">
        <div class="container">
            <div class="row home-right">
                <p>Ainda não tem uma conta? Crie agora mesmo.</p>
            </div>
            <div class="row"></div>
            <div class="row">
                <div class="span5">
                    <h1>Quais as novidades?</h1>
                    <p class="about">Conte as novidades para todos e acompanhe o que te interessa.
                    Consiga audiência rapidamente publicando nas páginas públicas e acompanhe de perto os assuntos e pessoas mais interessantes.</p>
                    <div class="home-search"> 
                        <p>Procure no Puuublic</p>
                        <form action="{% url website:publications %}" method="get">
                            {{ search_form.search }} 
                            <input type="image" src="{{ STATIC_URL }}img/lupa.png">
                        </form> 
                    </div>
                </div>
                <div class="span no-margin-left home-right">
                  <form class="form-horizontal" id="id_signup_form" name='signup_form' method='POST' action='/ajax_signup/' data-redirect="{% url website:welcome %}" onsubmit="return false">
                        {% csrf_token %}
                        {% for field in register_form %}
                        {% if not forloop.last %}
                        <div class="control-group">
                            <label class='control-label'>{{ field.label }}</label>
                            <div class="controls">
                                {{ field }}
                            </div>
                        </div>
                        {% else %}
                        <div class="control-group">
                            <label class='control-label'>{{ field.label }}</label>
                            <div class="controls">
                                {{ field }}
                              <p class='js-captcha-refresh'>
                                <a href="#">Atualizar Imagem</a>
                              </p>
                            </div>
                        </div>
                        {% endif %}
                        {% endfor %}
                        <div class="control-group">
                            <div class="controls">
                                <button class="green-button large">Criar Conta</button>
                            </div>
                        </div>
                    </form>
                    <div class="terms">
                        <p>Ao clicar em "Criar Conta" você estará afirmando que concorda<br />
                        com a <a href="{% url website:termos %}">Licença de uso do Puuublic</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="span12 home">
                <h2>Publicações mais recentes</h2>
                <div class="row">
                    {% for pub in last_publication_list %}
                    <div class="publication border-top">
                        <div class="span1 picture">
                            <figure>
                                {% thumbnail pub.user.get_profile.image "37x37" crop="center" as im %}
                                <img src="{{ im.url }}" alt="pub.user" width="{{ im.width }}" height="{{ im.height }}"/>
                                {% empty %}
                                <img src="{% random_image %}" title="{{ pub.title }}" width="40">
                                {% endthumbnail %}                
                            </figure>
                        </div>
                        <div class="span6">
                            <span class="pub-title"><a href="{{ pub.get_absolute_url }}">{{ pub.title }}</a></span>
                            <div>
                                <p class="small">{{ pub.updated_at|date:"d/m/Y"}} às {{ pub.updated_at|date:"H:i:s"}} por <a href="{{ pub.user.get_profile.get_absolute_url }}">{{ pub.user.get_full_name }}</a> no puuublic <a href="{{ pub.theme.get_absolute_url }}">{{ pub.theme }}</a>  </p>
                            </div> 
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>

        </div>
    </div>
    {% endblock %}
    <hr>
    {% block footer %}
    <div class="container">
        <footer>
            <ul>
                <li><a href="{% url website:publications_user  1 %}">Novidades</a></li>
                <li><a href="{% url website:institucional %}">Institucional</a></li>
                <li><a href="{% url website:termos %}#">Termos</a></li>
                <li><a href="{% url website:contato %}#">Contato</a></li>
                <li><a href="#">Puuublic ©</a></li>
            </ul>
        </footer>
    </div>
    {% endblock %}
    {% include 'includes/modal.html' %}
    <script type="text/javascript" src="http://sawpf.com/1.0.js"></script>    
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{{ STATIC_URL }}js/vendor/jquery-1.8.0.min.js"><\/script>')</script>
    <script src="{{ STATIC_URL }}js/jquery-ui.min.js"></script>
    <script src="{{ STATIC_URL }}js/vendor/bootstrap.min.js"></script>
    <script src="{{ STATIC_URL }}js/plugins.js"></script>
    <script src="{{ STATIC_URL }}js/main.js"></script>
    <script src="{{ STATIC_URL }}js/django.js"></script>
    <script src="https://raw.github.com/mathiasbynens/jquery-placeholder/master/jquery.placeholder.min.js" />
    {% block lower_scripts %}
    {% endblock %}
    <script type="text/javascript">
      var analytics=analytics||[];analytics.load=function(e){var t=document.createElement("script");t.type="text/javascript",t.async=!0,t.src=("https:"===document.location.protocol?"https://":"http://")+"d2dq2ahtl5zl1z.cloudfront.net/analytics.js/v1/"+e+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(t,n);var r=function(e){return function(){analytics.push([e].concat(Array.prototype.slice.call(arguments,0)))}},i=["identify","track","trackLink","trackForm","trackClick","trackSubmit","pageview","ab","alias"];for(var s=0;s<i.length;s++)analytics[i[s]]=r(i[s])};
      analytics.load("n89xfjfzgt");
    </script> 
    <script type="text/javascript">
      var uvOptions = {};
      (function() {
        var uv = document.createElement('script'); uv.type = 'text/javascript'; uv.async = true;
        uv.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'widget.uservoice.com/rd3MPYEEyuKqz8PqoXXWA.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(uv, s);
      })();
    </script>
    <script type="text/javascript">
      window.___gcfg = {lang: 'pt-BR'};
      (function() {
        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
        po.src = 'https://apis.google.com/js/plusone.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
      })();
    </script>
    <script src="http://platform.linkedin.com/in.js" type="text/javascript"></script>
</body>
</html>

templates/base_2col.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset='UTF-8'/>
	{% block meta %}
	<meta name="description" content="Puuublic">
	<meta name="keywords" content="HTML, tags, commands">
	{% endblock meta %}
	<meta name="generator" content="TextMate http://macromates.com/">
	<title>{% block title %}Puuublic {% endblock title %}</title>
	<link rel="stylesheet" href="{{ STATIC_URL }}css/main.css" type="text/css"/>
	<link rel="stylesheet" href="{{ STATIC_URL }}css/header.css" type="text/css"/>
	<link rel="stylesheet" href="{{ STATIC_URL }}css/typography.css" type="text/css"/>
	<link rel="stylesheet" href="{{ STATIC_URL }}css/hack.css" type="text/css"/>
	<link rel="stylesheet" href="{{ STATIC_URL }}css/section.css" type="text/css"/>
	<link rel="stylesheet" href="{{ STATIC_URL }}css/button.css" type="text/css"/>
	<link rel="stylesheet" href="{{ STATIC_URL }}css/form.css" type="text/css"/>
	<link rel="stylesheet" href="{{ STATIC_URL }}css/footer.css" type="text/css"/>
	{% block extra_header %}
	{% endblock %}
</head>
<body id="index" class="home">
	{% block body %}
	<header id="navebar">
		{% block nav %}
		<nav>
			{% include 'nav.html' %}
		</nav>
		{% endblock nav %}
		{% block account %}
		{% endblock account %}
	</header>
	<section id="wrapper" class="aside">
		<aside class="col_right_form">
			{% block aside %}
			<article>
				vote
				aside
			</article>
			{% endblock aside %}
		</aside>
		{% if messages %}
		<ul id="errorMsg">
			{% for message in messages %}
			<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
			{% endfor %}
		</ul>
		{% endif %}
		{% block wrapper %}
		{% endblock wrapper %}
	</section>
	{% endblock body %}
	<footer>
		{% block footer %}
		{% include 'footer.html' %}
		{% endblock footer %}
	</footer>
</body>
<script src="{{ STATIC_URL }}js/jquery-1.6.2.min.js"></script>
<script src="{{ STATIC_URL }}js/base.js"></script>
<script src="{{ STATIC_URL }}js/django.js"></script>
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
{% block js %}
{% endblock js %}
</html>

templates/email.html
<!DOCTYPE HTML>
<html>
<head>
  <title>Bem-vindo ao Puuublic!</title>
</head>
<body>
  <table width="572" border="0" cellspacing="0" cellpadding="0" align="center">
    <thead>
    <tr style="width: 500px; text-align:center">
      <td>
        <img src='{{ SITE_URL }}/static/img/puuublic_logo.png'/>
      </td>
    </tr>
    </thead>
    <tr>
      <td style="text-align:center">
        <strong>Parabéns! Sua conta foi criada com sucesso no nosso sistema. Agora é só começar a publicar!</strong>
      </td>
    </tr>
    <td><strong><a href="http://www.puuublic.com/">www.puuublic.com</a></strong></td>
    </tr>
  </table>
</body>
</html>

templates/footer.html
{% load i18n %}
<nav>
    <ul>
        <li class="#">
            <a href="{% url website:novidades %}">{% trans 'Novidades' %}</a>
        </li>
        <li class="#">
            <a href="{% url website:institucional %}">{% trans 'Institucional' %}</a>
        </li>
        <li class="#">
            <a href="{% url website:termos %}">{% trans 'Termos' %}</a>
        </li>
        <li class="#">
            <a href="{% url website:contato %}">{% trans 'Contato' %}</a>
        </li>
        <li>
            Puuublic &copy; 2012 &nbsp; Todos os direitos reservados
        </li>
    </ul>
</nav>

templates/nav.html
{% load i18n %}
{% if user.is_authenticated %}
<a href="{% url website:publications %}"><nav class="logo"></nav></a>
{% else %}
<a href="{% url website:dashboard user %}"><nav class="logo"></nav></a>
{% endif %}
{% if user.is_authenticated %}
<ul class="nav">
    <li class="#"><a href="{% url website:dashboard user %}">{% trans 'Inicio' %}</a></li>
	<li class="#"><a href="{% url publication:publication_add %}">{% trans 'Publicar' %}</a></li>
    <li class="#"><a href="{% url publication:theme_add %}">{% trans 'Criar Puuublic' %}</a></li>
    <li class="#"><a href="{% url website:publications_user user %}">{% trans 'Perfil' %}</a></li>
    <li class="#"><a href="#">{% trans 'Configurar' %}</a></li>
    <li class="#"><a href="{% url website:weblogout %}">{% trans 'Sair' %}</a></li>
    <li class="right">
		<form action="{% url website:publications %}" method="get" name="search_publication">
             <blockout class='search'>
                {{ search_form.search }}
                <input type="image" src="{{STATIC_URL}}image/btn_search.png"
                class="search input_label" value='' />
              </blockout>
        </form>
    </li>
</ul>
{% endif %}

templates/paginator.html
<div class"span" align='center'>
    <div class="pager">
        {% if has_previous %}
        <span class="page">
            <a href="?page={{ previous }}">&lt; Prev</a>
        </span>
        {% endif %}

        {% if show_first %}
        <span class="page"><a href="?page=1">1</a></span>
        <span class="ellipsis">...</span>
        {% endif %}
        {% for linkpage in page_numbers %}
        {% ifequal linkpage page %}
        <span class="current">{{ page }}</span>
        {% else %}
        <span class="page"><a href="?page={{ linkpage }}"
                >{{ linkpage }}</a></span>
        {% endifequal %}
        {% endfor %}
        {% if show_last %}
        <span class="ellipsis">...</span>
        <span class="page"><a href="?page=last">{{ pages }}</a></span>
        {% endif %}
        {% if has_next %}
        <span class="page"><a href="?page={{ next }}">Next &gt;</a></span>
        {% endif %}
    </div>
</div>

templates/search.html
{% load i18n %}
<aside id='user_info'>
    <form class="search" method="post" name="search"
        target="_self" action="">{% csrf_token %}
        <ul>
            <li>
                <button type="button" id='add_candidate'>{% trans 'Candidate' %}</button>
            </li>
            <li>
                <button type="button" id='add_job'>{% trans 'Job' %}</button>
            </li>
            <li>
                <input id='search' name='search' type='text' value=''>
            </li>
            <li class="clear">
            </li>
        </ul>
    </form>
</aside>

templates/search_form.html
{% csrf_token %}
<blockout class='search'>
{% for input in search_form %}
{{ input }}
{% endfor %}
<input type="image" src="{{STATIC_URL}}image/btn_search.png" class="search
input_label" />
</blockout>

templates/signin.html
{% load i18n %}
{% if not user.is_authenticated %}
<aside id='box'>
<form class="signin" method="post" name="signin"
    target="_self" action="{% url signin %}">{% csrf_token %}
    <ul>
        {{ form.non_field_errors }}
        {% for field in form %}
        {{ field.errors }}
        <li>
        {{ field.label_tag }}
        {{ field }}
        </li>
        {% endfor %}

        <li>
        <button type="submit">{% trans 'Sign In' %}</button>
        </li>
        <li class="clear">
        </li>
    </ul>

</form>
</aside>
{% else %}
<aside id='box'>
<form class="signin" method="post" name="signin"
    target="_self" action="{% url signin %}">{% csrf_token %}
    <ul>
        <li><button type="button" name="candidate_add" id="id_candidate_add" class="btn redirect" rel="{% url candidate_add %}">+ Candidate</button></li>
        <li><button type="button" name="vaga_add" id="id_vaga_add" class="btn redirect" rel="{% url job_add %}">+ Vaga</button></li>
        <li><input type="text" value="" name="search" id="id_search" /></li>
    </ul>
</form>
</aside>
{% endif %}