publication/urls.py
#!/usr/bin/env python
# encoding: utf-8
"""
urls.py

Created by Valder Gallo on 2012-01-29.
Copyright (c) 2012 valdergallo. All rights reserved.
"""

from django.conf.urls.defaults import patterns, url

puuublic/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps import GenericSitemap

from filebrowser.sites import site
admin.autodiscover()

from website.views import EmailView
from website.sitemap import sitemaps
from website.feed import RssSiteNewsFeed, AtomSiteNewsFeed
from publication.models import Publication

news = {
    'googlenews': GenericSitemap({
        'queryset': Publication.objects.order_by('-created_at'),
        'limit': 0.5,
        'changefreq': 'daily',
        'date_field': 'created_at'
    }),
}

urlpatterns = patterns('',
    url(r'^public_admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^public_admin/varnish/', include('varnishapp.urls')),
    url(r'^public_admin/', include(admin.site.urls)),
    url(r'^public_admin/filebrowser/', include(site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^email-template/?$', EmailView.as_view()),
    url(r'^sitemap-googlenews\.xml$', 'django.contrib.sitemaps.views.sitemap',
        { 'sitemaps': news , 'template_name': 'sitemap_googlenews.xml' }),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.index', {
        'sitemaps': sitemaps,
    }),
    url(r'^sitemap-(?P<section>.+)\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    url(r'^rss/$', RssSiteNewsFeed()),
    url(r'^atom/$', AtomSiteNewsFeed()),
    url(r'^', include('website.urls', app_name='website', namespace='website')),
)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
#!/usr/bin/env python
# encoding: utf-8

from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('website.views',
    url(r'^$', 'home', name='home'),
    url(r'^recuperar/(?P<user_id>\d+)/(?P<token_dev>\w+)/$', 'recover', name='recover_pass'),
    url(r'^publicacoes/$', 'publications', name='publications'),
    url(r'^dashboard/$', 'dashboard', name='dashboard'),
    url(r'^ajax_login/$', 'ajax_login', name='ajax_login'),
    url(r'^ajax_signup/$', 'ajax_signup', name='ajax_signup'),
    url(r'^ajax_recover/$', 'ajax_recover', name='ajax_recover'),
    url(r'^logout/$', 'weblogout', name='weblogout'),
    url(r'^institucional/$', 'institucional', name='institucional'),
    url(r'^termos/$', 'termos', name='termos'),
    url(r'^contato/$', 'contato', name='contato'),
    url(r'^conta/$', 'acc_config', name='acc_config'),
    url(r'^bem-vindo/$', 'welcome', name='welcome'),
    url(r'^perfil/(?P<user_id>\w+)/$', 'publications_user', name='publications_user'),
)

urlpatterns += patterns('publication.views',
    url(r'^ajax_add_favorite/$', 'ajax_add_favorite', name='ajax_add_favorite'),
    url(r'^puuublic/adicionar/$', 'publication_add', name='publication_add'),
    url(r'^puuublic/tema/adicionar/$', 'theme_add', name='theme_add'),
    url(r'^publicacao/puuublic/buscar/json/$', 'ajax_theme_search', name='ajax_theme_search'),
    url(r'^(?P<theme_slug>[\w-]+)/(?P<publication_slug>[\w-]+)/editar/$', 'edit_publication', name='edit_publication'),
    url(r'^(?P<theme_slug>[\w-]+)/(?P<publication_slug>[\w-]+)/$', 'publication_detail', name='publication_detail'),
    url(r'^(?P<theme_slug>[\w-]+)/$', 'theme_page', name='theme_page'),
)

publication/forms.py
#!/usr/bin/env python
# encoding: utf-8
from django.conf import settings
from django import forms
from django.db.models import Q
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

from publication.models import Publication, Theme, Comment

from bs4 import BeautifulSoup
from ckeditor.widgets import CKEditorWidget

class SearchForm(forms.Form):
    "Search values on Publication content everywere"
    search = forms.CharField(max_length=100, required=False,\
        widget=forms.TextInput(attrs={'placeholder':'Busque aqui..',\
            'class':'search-large'} ))

    def get_result_queryset(self):
        query = Q()
        value = self.data.get('search', '')
        #_filter = self.data.get('filter', 'publication')

        #if _filter == 'publication':
        query |= Q(title__icontains=value)
        query |= Q(theme__title__icontains=value)
        query |= Q(message__icontains=value)
        query |= Q(tags__name__icontains=value)
        publications =  Publication.objects.select_related('themes').filter(query).order_by('-created_at')
        query = Q()

        #if _filter == 'puuublic':
        query |= Q(title__icontains=value)
        themes =  Theme.objects.filter(query)
        
        query = Q()
        #if _filter == 'people':
        query |= Q(first_name__icontains=value)
        query |= Q(last_name__icontains=value)
        query |= Q(username__icontains=value)

        people = User.objects.filter(query)

        count = publications.count() + themes.count() + people.count()
        return {
            'publications':publications,
            'people':people,
            'themes':themes,
            'count':count
        }


class PublicationForm(forms.ModelForm):
    "Add new Publication"
    theme_name = forms.CharField(label=u"Nome do Puuublic",max_length=50,\
        required=True,widget=forms.TextInput(attrs={'class':'theme-large'}),\
        error_messages={
            'required':u'Escolha um puuublic',
        })

    title = forms.CharField(widget=forms.TextInput(attrs={'class':'theme-large'}),\
        error_messages={
            'required':u'Escolha um Título'
        })

    message = forms.CharField(widget=CKEditorWidget(attrs={'cols': 80, 'rows': 30}),
            error_messages={'required':u'Digite uma mensagem'}
        )


    class Meta:
        model = Publication
        fields = ('theme_name','title', 'message', 'image')

    def clean_message(self):
        message = self.cleaned_data.get('message')
        #links externos adicionando _blank
        soup = BeautifulSoup(message)
        for link in soup.findAll('a'):
            link.attrs['target'] = '_blank'
        return unicode(soup)


    def clean_theme_name(self):
        title = self.cleaned_data['theme_name']
        try:
            Theme.objects.get(title=title)
        except Theme.DoesNotExist:
            raise forms.ValidationError(u'Tema Inválido')

        return title

    def clean_image(self):
        image = self.cleaned_data.get('image')
        if image:
            if image._size > settings.MAX_UPLOAD_SIZE:
                raise forms.ValidationError(u'Tamanho limite da imagem: 3MB')
        return image


    def save(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        theme = Theme.objects.get(title=self.cleaned_data['theme_name'])
        instance =  super(PublicationForm, self).save(commit=False)
        if not instance.slug:
            nslug = slugify(self.cleaned_data['title'])
            c = 0
            while Publication.objects.filter(theme=theme,slug=nslug).count() > 0:
                c += 1
                nslug = '%s-%d'%(nslug, c)
            instance.slug = nslug
        if user:
            instance.user = user
        if theme:
            instance.theme = theme
        instance.save()
        return instance



class ThemeForm(forms.ModelForm):
    "Create a new puublic"
    title = forms.CharField(max_length=50, required=True,\
        widget=forms.TextInput(attrs={\
            'class':'theme-large',
        }))

    def clean_title(self):
        title = self.cleaned_data['title']
        placeholder = u'Digite o nome do novo puuublic (Máximo 50 caracteres)'
        if title == '' or title == placeholder:
            raise forms.ValidationError(u'Digite um título')

        return title

    class Meta:
        model = Theme
        fields = ('title',)

class CommentForm(forms.ModelForm):
   
    message = forms.CharField(label=u"Mensagem",max_length=200,widget=forms.TextInput(attrs={
            'class':'theme-large',
        }))
 
    class Meta:
        model = Comment
        fields = ('message',)

publication/views.py
#!/usr/bin/env python
# encoding: utf-8
"""
views.py

Created by Valder Gallo on 2012-01-29.
Copyright (c) 2012 valdergallo. All rights reserved.
"""

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.template.defaultfilters import slugify


from publication.forms import PublicationForm, ThemeForm, \
    CommentForm
from publication.models import Publication, Theme, Favorites
import simplejson

@login_required
def publication_add(request):
    if request.method == 'POST':
        publication_form = PublicationForm(request.POST, request.FILES)
        if publication_form.is_valid():
            instance = publication_form.save(user=request.user)
            instance.save()
            publication_form.save_m2m()
            url = instance.get_absolute_url()
            return redirect(url)
            #return HttpResponse(simplejson.dumps({'status':True,'url':url})) 
        """
        else:
            errors = publication_form.errors
            return HttpResponse(simplejson.dumps({'status':False,'errors':errors}))
        """
    else:
        if request.GET.get('theme',False):
            theme_name = request.GET.get('theme')
            theme = get_object_or_404(Theme,slug=theme_name)
            publication_form = PublicationForm(initial={'theme_name':theme.title,'theme_id':theme.id })
        else:
            publication_form = PublicationForm()

    return render(request,
                  "publication/publication_form.html",
                  {'publication_form': publication_form},
                  )


@login_required
def edit_publication(request, theme_slug,publication_slug):
    publication = get_object_or_404(Publication, slug=publication_slug,\
        user=request.user)
    theme = get_object_or_404(Theme,slug=theme_slug)
    if request.method == 'POST':
        publication_form = PublicationForm(request.POST,\
            request.FILES,instance=publication)
        if publication_form.is_valid():
            publication_form.save()
            publication_form.save_m2m()
            return redirect('website:publication_detail', theme_slug=theme.slug,
                publication_slug=publication.slug)

    else:
        publication_form = PublicationForm(instance=publication,\
            initial={'theme_name':theme.title})

    return render(request,"publication/publication_form.html",{
                'publication_form': publication_form,
            })


#@login_required
def publication_detail(request, theme_slug, publication_slug):
    theme = get_object_or_404(Theme,slug=theme_slug)
    publication = get_object_or_404(Publication,theme=theme,slug=publication_slug)
    comments = publication.comments_set.all() 
    
    if request.method == "POST":
        form_comment = CommentForm(request.POST)
        if form_comment.is_valid():
            instance = form_comment.save(commit=False)
            instance.user = request.user
            instance.publication = publication
            instance.save()
            messages.success(request, 'Comentário adicionado com sucesso')
    else:
        form_comment = CommentForm()
    print publication.user.get_profile().get_url
    return render(request,"publication/publication_detail.html",{
                      'publication': publication,
                      'form_comment':form_comment,
                      'comments':comments
                  })


#@login_required
def theme_page(request,theme_slug):
    """
    Pagina de um tema
    """
    try:
        theme = Theme.objects.get(slug__exact=theme_slug)
    except Theme.DoesNotExist:
        form = ThemeForm()
        page = request.REQUEST.get('page', 1)
        pub_list = []
        pub_last_update = Publication.objects.all().order_by('-created_at')[0:20]
        return render(request,'publication/theme_form.html',{
            'theme_slug':theme_slug,
            'theme_form': form,
            "pub_list": pub_list,
            "pub_last_update": pub_last_update,
            "page": page
        })
    #theme = get_object_or_404(Theme,slug=theme_slug)
    page = request.REQUEST.get('page', 1)
    pub_list = Publication.objects.filter(theme=theme).order_by('-created_at')[0:20]
    
    return render(request,
                  "publication/theme_page.html",
                    {
                    "theme": theme,
                    "pub_list": pub_list,
                    "page": page
                     }
                  )


@login_required
def theme_add(request):
    
    if request.method == "POST":
        theme_form = ThemeForm(request.POST)
        if theme_form.is_valid():
            slug = slugify(theme_form.cleaned_data['title']) 
            if Theme.objects.filter(slug__exact=slug).count() > 0:
                url = reverse("website:theme_page",\
                    kwargs={'theme_slug':slug})
                return HttpResponse(simplejson.dumps({'status':True,'url':url}))
            instance = theme_form.save(commit=False)
            instance.user = request.user
            instance.slug = slugify(instance.title)
            instance.save()
            url = reverse("website:theme_page",\
                kwargs={'theme_slug':instance.slug})
            return HttpResponse(simplejson.dumps({'status':True,'url':url}))
        else:
            errors = theme_form.errors
            return HttpResponse(simplejson.dumps({'status':False,'errors':errors}))
    else:
        theme_form = ThemeForm()

    return render(request,
              "publication/theme_form.html",
              {
                'theme_form': theme_form,
                },
              )

def ajax_theme_search(request):
    """
    Retorna um json com os temas
    """

    result = {}
    result['status'] = False
    q = request.GET.get('term',None)
    if q:
        themes = Theme.objects.filter(title__icontains=q)
        """
        l_theme = []
        for t in themes:
            l_theme.append({'title': t.title, 'id': t.id})

        result['themes'] = l_theme
        result['status'] = True
        """
        theme_list = [i.title for i in themes]
    return HttpResponse(simplejson.dumps(theme_list), mimetype="application/json")


def ajax_add_favorite(request):
    if not request.is_ajax():
        return HttpResponse(':)')

    if request.method == "POST":
        theme_id = request.POST.get('key')
        theme = get_object_or_404(Theme, pk=int(theme_id))
        try:
            fav = Favorites.objects.get(user=request.user, theme=theme)
            print "achou"
            print fav
        except Favorites.DoesNotExist:
            fav = Favorites.objects.create(user=request.user, theme=theme)
            print "criou"
            print fav
            return HttpResponse(simplejson.dumps({'status': True,
                                                  'action': 'add'}),
                                mimetype="application/json")
        fav.delete()
        return HttpResponse(simplejson.dumps({'status': True,
                                              'action': 'remove'}),
                            mimetype="application/json")
    else:
        return HttpResponse(':)')

publication/templates/publication/public_detail.html
{% extends 'base.html' %}
{% load i18n thumbnail default_image %}

{% block wrapper %}
<aside class="col_right_form">
    <section class="recently_publication_list">
        <h4>Publicationações mais recentes</h4>
        {% for pub in user.Publications.must_popular %}
        <article>
            {% thumbnail pub.image "38" as im %}
            <figure>
                <img src="{{ im.url }}" title="{{ pub.title }}" width="{{ im.width }}" height="{{ im.height }}">
            </figure>
            {% empty %}
            <figure>
                <img src="{% random_image %}" title="{{ pub.title }}" width="38">
            </figure>
            {% endthumbnail %}
            <h5>{{ pub.title }}</h5>
            {{ pub.message|truncatewords_html:9 }}
            <div align="right">
                no puuublic <a href="#">{{ pub.user.username }}</a>
            </div>
        </article>
        {% endfor %}
    </section>
</aside>
<section class="form_Publication">
    <h1>{{ publication.title }}</h1>
    {% thumbnail Publication.image "950x200" as im %}
    <figure>
        <img src="{{ im.url }}" title="{{ pub.title }}" width="{{ im.width }}" height="{{ im.height }}">
    </figure>
    {% endthumbnail %}
    {{ publication.message|safe }}
    <div class="edit_bar">
        EDIT BAR
    </div>
    <h4> Commentar esta Publicationação </h4>
    <form action="" name="form_comment" id="id_form_comment">
        {{ form_comment.as_p }}
        <button type="submit">
            Enviar
        </button>
    </form>
    <section class="comments">
        <h4>Comentários ({{ publication.comments.count|default:0 }})</h4>
        {% for comment in Publication.comments.last_ten %}
        <article>
            {% thumbnail comment.user.get_profile.image "67" as im %}
            <figure>
                <img src="{{ im.url }}" title="{{ pub.title }}" width="{{ im.width }}" height="{{ im.height }}">
            </figure>
            {% empty %}
            <figure>
                <img src="{{ default.image.url }}" title="{{ pub.title }}" width="{{ default.image.width }}" height="{{ default.image.height }}">
            </figure>
            {% endthumbnail %}
            {{ comment.message }}
        </article>
        {% endfor %}
    </section>
</section>
{% endblock wrapper %} 

publication/templates/publication/public_form.html
{% extends 'base.html' %}
{% load i18n %}

{% block wrapper %}
<aside class="col_right_form">
	<h4>Quais as novidades?</h4>
	<p>Algumas dicas podem ajudá-lo a responder essa pergunta. Primeiro, tome cuidado com o título,  ele deve contextualizar o leitor sobre o tema geral e estimular a leitura. Seja objetivo e procure incluir palavras que definam o conteúdo da Publicationação.</p>
	<p>E o mais importante: a prática leva à perfeição.</p>
	<p>A qualidade do seu texto irá evoluir com a prática, assim como as possibilidades de se expressar. Além disso, exercitar a escrita pode ser muito prazeroso. O que está esperando? Mãos à obra e bons textos.Caso use textos de outros autores, lembre-se sempre de citar seus nomes no final da Publicationação, assim você evita problemas autorais.</p>
	<p>Use vídeos de curta duração, divida-os em partes se necessário, pois nem todos os seus leitores possuem acesso à Internet de alta velocidade.</p>
	<p>Use imagens para complementar as informações. Elas são um elemento essencial de persuasão.</p>
	<p>Escreva em blocos. Na medida do possível restrinja cada parágrafo a uma idéia, como foi feito nesse texto que você lê agora.</p>
	<p>Depois de esclarecer as questões principais, descreva os aspectos secundários. Não há limite para a extensão do texto, desde que ele seja de fácil entendimento e interesse ao leitor.</p>
	<p>Seja sucinto no texto. Aborde o aspecto mais importante do que deseja falar logo no primeiro parágrafo. Deixe claro qual o assunto, quando ocorreu, quem envolveu, como, onde e o porquê.</p>
</aside>

<section class="form_Publication">
<h4>Crie uma nova Publicationação</h4>
<form action="{% url publication:publication_add %}" method="POST" name="publication_add" enctype="multipart/form-data" >
	{% csrf_token %}
    {{ publication_form.as_p }}
    <button type="submit">Publicationar</button>
</form>
</section>

{% endblock wrapper %}

publication/templates/publication/publication_detail.html
{% extends 'base.html' %}
{% load i18n thumbnail default_image endless %}
{% block title%}
Puuublic - {{ publication.title|title }}
{% endblock%}

{% block extra_meta %}
<meta name="author" content="{{ get_user.get_full_name|title }}"/>
<meta name="description" content="{{ publication.title }}">
<meta name="keywords" content="html, puuublic, {{ publication.theme.title}}, {{publication.title}}">
{% endblock %}

{% block ogtags %}
{% if publication.image %} 
{% thumbnail publication.image "200x200" as im %}
<meta property="og:image" content="http://puuublic.com{{ im.url }}"/>
{% endthumbnail %}
{% endif %}
<meta property="og:title" content="{{ publication.title }}"/>
<meta property="og:type" content="article"/>
<meta property="og:site_name" content="Puuublic"/>
<meta property="og:url" content="{{ publication.url }}"/>
<meta property="article:author" content="{{ get_user.get_full_name|title }}">
<meta property="article:section" content="{{ publication.theme.title|capfirst }}">
{% endblock %}

{% block seo %}
<meta itemprop="name" content="{{ publication.title }}">
<meta itemprop="description" content="{{ publication.title }}">
<meta name="twitter:card" content="summary">
<meta name="twitter:url" value="{{ publication.url }}">
<meta name="twitter:title" value="{{ publication.title }}">
{% if publication.image %}
{% thumbnail publication.image "320x200" as im %}
<meta name="twitter:image" value="http://puuublic.com{{ im.url }}">
{% endthumbnail %}
{% endif %}
{% endblock%}


{% block main %}
<div class="container publication-page" >
    <div class="row">
        <div class="span12" itemscope itemtype="http://schema.org/Article">
          <h2 itemprop="name">{{ publication.title }}</h2>
          <p class="small">
          <time itemprop="datePublished" datetime="{{ publication.updated_at|date:"Y-m-d"}}">
          {{ publication.updated_at|date:"d/m/Y"}}
          </time> 
          às {{ publication.updated_at|date:"H:i:s"}} por <a rel="author" itemprop="author" alt="{{ publication.user.get_full_name|title }}" href="{{ publication.user.get_profile.get_absolute_url }}">{{ publication.user.get_full_name }}</a> no puuublic <span itemprop="articleSection"><a href="{{ publication.theme.get_absolute_url }}">{{publication.theme.title|capfirst}}</a></span></p>
            {% include 'includes/social.html' %}
            {% if publication.image %}
            <figure>
                {% thumbnail publication.image "400" as im %}
                <img itemprop="thumbnailUrl" src="{{ im.url }}" title="{{ pub.title }}" width="{{ im.width }}" />
                {% endthumbnail %}
            </figure>
            {% endif %}
            <br/>
            <div itemprop="articleBody">
              {{ publication.message|safe }}
            </div>
            {% if user.is_authenticated %}
            <h3>Comente esta Publicação </h3>
            <form action="" method="post" name="form_comment" id="id_form_comment">{% csrf_token %}
                {{ form_comment.message }}
                <button type="submit" class="green-button">
                    Enviar
                </button>
            </form>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="span12">
            <h3 style="font-size:13px">Comentários ({{ comments.count|default:0 }})</h3>
            {% paginate comments %}
            {% for comment in comments %}
            <div class="row comments">
                 <div class="span">
                {% thumbnail comment.user.get_profile.image "37x37" crop="center" as im %}
                <figure>
                    <a href="{% url website:publications_user comment.user.id %}">
                        <img src="{{ im.url }}" title="{{ pub.title }}" width="{{ im.width }}" height="{{ im.height }}">
                    </a>
                </figure>
                {% empty %}
                <figure>
                    <a href="{% url website:publications_user comment.user.id %}">
                    <img src="{% random_image %}" title="{{ pub.title }}" width="37" height="37" >
                    </a>
                </figure>
                {% endthumbnail %}
                </div>
                <div class="span6">
                {{ comment.message|urlize }}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<br/>
{% endblock  %} 

publication/templates/publication/publication_form.html
{% extends 'base.html' %}
{% load i18n %}

{% block extrajs %}
{{ publication_form.media }}
{% endblock %}

{% block main %}
<div class="container publication-add">
    <div class="row">
        {% if publication_form.errors %}
        <div class="alert alert-error">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <h4 class="alert-heading">Alguns erros foram encontrados</h4>
            <ul>
            {% for field in publication_form %}
            {% if field.errors %}
            <li>{{ field.errors|striptags }}</li>
            {% endif %}
            {% endfor %}
            </ul>
        </div>
        {% endif %}
        <form action="." method="POST"  enctype="multipart/form-data">
        <div class="span12">
            <h2>Quais as novidades?</h2>
                <hr/>
                {% csrf_token %}
                <label for="id_theme_name"><i class="icon-file"></i> Escolha um Puuublic</label>
                {{ publication_form.theme_name }}
                <label for="id_theme_name"><i class="icon-pencil"></i> Escolha um Título</label>
                {{ publication_form.title }}
                <label for="id_theme_name"><i class="icon-pencil"></i> Digite o texto</label>
                {{ publication_form.message }}
                <p></p>
        </div>
        <div class="span12">
            <div class="row">
                <div class="span7">
                {{ publication_form.image }}
                </div>
                <div class="span5 config-right">
                    <button class="green-button large" type="submit">Publicar</button>
                </div>
            </div>
        </div>
        </form>
    </div>
</div>
<br/>
{% endblock  %}

publication/templates/publication/theme_form.html
{% extends 'base.html' %}
{% load i18n %}

{% block main %}
<div class="container theme-add">
	<h2>Crie um novo Puuublic</h2>
    <hr/>
    <p>Escolha um nome que defina bem o assunto e lembre-se que puuublics são páginas públicas, e todos poderão publicar nelas.</p>
    <br/>
    {% if theme_slug %}
    <h3>Você pode criar o tema {{ theme_slug }} agora! Preencha o formulário abaixo e clique em criar.</h3>
    {% endif %}
    <div class="row">
        <div class="span12">
            <p><i class="icon-file"></i> Digite o nome do novo puuublic</p>
            <form id="themeForm" action="{% url website:theme_add %}" method="POST" onsubmit="return false" >
                {% csrf_token %}
                {{ theme_form.title }}
        </div>
    </div>
    <div class="row">
        <div class="span6">
             <div class='auto_url'>
                <p>O endereço deste puuublic será:</p>
                <a href='#'>http://puuublic.com/</a>
            </div>
        </div>
        <div class="span6 config-right">
            <span class="remaining"></span> 
            <button class="green-button" type="submit">Criar</button>
        </div>
        </form>
    </div>
</div>
<br/>
{% endblock  %}